### ISSUE TITLE
Safari: Clicking text in closed, unfocused select does not open menu

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#122]
Please walk through the following steps for reporting an issue about Orion:

## Short description of your issue:

-- When following the `Open Menu via Mouse` in Safari 10, I found a bug where the menu doesn't open if you click the text of the button. It opens every time if you click the 'edge' of the menu button outside of the text. See screenshot:

<img width="502" alt="screenshot 2017-02-08 15 31 43" src="https://cloud.githubusercontent.com/assets/22905/22762347/c54ead04-ee13-11e6-9d99-f03855e89f8c.png">

Clicking anywhere outside the red box produces the desired state tranisition.

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Launch react-playground
2. Click inside the box (see image)
3. Observe that the menu does not open

Expected outcome: the button opens.

## What browsers are affected?

Safari 10

## Which Orion version is affected?

New Issue

Blocks #45

**Comment by aneyzberg** [comment]
@camwest The fix for this bug came in with the fix for #124.
