### ISSUE TITLE
Firefox, Edge: Choosing an option with the mouse does not work

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#124]
Please walk through the following steps for reporting an issue about Orion:

## Short description of your issue:

When clicking an option with the mouse in Firefox or Microsoft Edge the browser does not select the correct option. This happens in both React and Angular playgrounds.

* In Firefox it seems to freeze the browser, showing the spinning wheel of doom in Mac OS.
* In Edge the menu disappears instantly but the previously selected option persists

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Visit react-playground in Firefox or Edge
2. Open the menu
3. Attempt to select an option

## What browsers are affected?

Firefox
Microsoft Edge

## Which Orion version is affected?

Unknown

Blocks #46

**Comment by aneyzberg** [comment]
@camwest The fix for this has been merged.
