### ISSUE TITLE
Hovering disabled option should not remove focus from previous option

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#148]
Please walk through the following steps for reporting an issue about Orion:

## Short description of your issue:

When you have an option disabled and you hover mouse over it it removes the focus from a previously selected option. This is bad since keyboard support becomes broken until you use the mouse to set focus to another option.

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Visit https://cdn.web-platform.io/orion-ui/orion/snapshot-master/react-playground/index.html
2. Open the select menu
3. Hover the mouse over X-small (disabled option)
4. Press the keyboard up or down arrow

Expected: focus should remain on the "Small" option and navigation should work as expected.

## What browsers are affected?

All browsers

## Which Orion version is affected?

N/A

Blocks #47

**Comment by aneyzberg** [comment]
@camwest Is this still an issue? @nfiniteset and I just looked at the link you provided above. And it appears to be working correctly.

**Comment by camwest** [comment]
Looks like it was fixed.
