### ISSUE TITLE
MS Edge shows input clear button which puts datepicker into a weird state

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#150]
Please walk through the following steps for reporting an issue about Orion:

## Short description of your issue:

![edge-clear-button](https://cloud.githubusercontent.com/assets/22905/23487577/da5ed99c-fe9b-11e6-8d3e-136911d3ed7d.gif)

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Visit https://cdn.web-platform.io/orion-ui/orion/snapshot-master/react-playground/index.html in MS Edge
2. Pick a date 
3. Click the clear button

Expected: clear button should not be visible at all!

## What browsers are affected?

MS Edge

## Which Orion version is affected?

Latest

Blocks #74

**Comment by aneyzberg** [comment]
completed by #154
