### ISSUE TITLE
 Setup S3 and CloudFront for snapshots

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#16]
```
As an orion developer
I want to view static data uploaded S3
So that I can deploy content to the internet
```

* [x] Set up circle specific IAM user on Internal AWS account with access to deploy to cdn.web-platform.io/orion-ui 
* [x] Configure circle AWS permissions with new IAM user account
* [x] Investigate if lerna can allow a sub-package to be used in the top level package.json
* [x] Write a script which moves all build directories from packages into top level build directory indexed by the package name
* [x] Write deploy script which uploads build directory from root of repo to the CDN and put it into `packages/scripts`
* [x] Review https://circleci.com/docs/fork-pr-builds/
* [x] Get react-playground npm run build working
* [x] Add GITHUB_TOKEN to circle
* [x] deploy-snapshot should update pull request github status with a link to the deployed index.html
* [x] `npm run deploy-snapshot` should run on PR
* [x] `npm run deploy-master` should run on master merge

See here for an example of what a snapshot deployment should look like (this is from our internal github). Clicking 'details' takes you to the index.html

<img width="1067" alt="screenshot 2017-01-10 13 57 52" src="https://cloud.githubusercontent.com/assets/22905/21826553/cf5f92ec-d73c-11e6-8e7c-5407eb99700b.png">

**Comment by camwest** [comment]
orion-circle-ci user credentials have been added to s3 with the following permissions:

```
"s3:PutObject", "s3:GetObject", "s3:PutObject", "s3:ListBucket"
```

Scoped to cdn.web-platform.io/orion-ui/*

**Comment by camwest** [comment]
I had to add `s3:ListBucket` to the `cdn.web-platform.io` bucket since it doesn't apply to sub resources

**Comment by camwest** [comment]
* React-playground npm run build won't work because components uses ES6 classes and react-playground uses uglify2 which doesn't support them
* We are going to add babel so we transpile the components to ES5 but unfortunately `window.customElements.define` requires an ES6 class or it throws at runtime. The polymer team wrote a shim to solve this problem here - https://github.com/webcomponents/custom-elements/blob/master/src/native-shim.js that I'm going to try to integrate.

**Comment by nfiniteset** [comment]
What's left on this story @camwest?

**Comment by camwest** [comment]
@nfiniteset I added three new tasks to the description

**Comment by camwest** [comment]
For reference: This is an example of how to update the github status for a PR from the 

```javascript
'use strict';

const appRoot = require('app-root-path').toString();
const pkg = require(`${appRoot}/package.json`);
const GitHubApi = require('github');
const ghUrlToObject = require('github-url-to-object');

/**
 * Returns a pre-configured GitHubApi instance
 */
function setupGithub(token) {
  const github = new GitHubApi({
    version: '3.0.0',
    host: 'git.autodesk.com',
    pathPrefix: '/api/v3'
  });

  github.authenticate({ type: 'oauth', token });

  return github;
}

/**
 * Creates a github pull request status update
 *
 * @param config.token - required, the github token for a user
 * @param config.sha - required, the github SHA for the same user
 * @param config.state - optional, current status for the state, can be one of: 'pending', 'success', 'failure', 'error'
 * @param config.context - optional, reference name of the status - pushing a new status with the same context will overwrite the previous
 * @param config.description - optional, short description of current status
 * @param config.targetUrl - optional, adds url as a link in github status update
 *
 */
module.exports = function createStatus(config) {
  return new Promise((resolve, reject) => {
    if (!config.token) {
      reject(new Error('must supply a token'));
    }

    if (!config.sha) {
      reject(new Error('must supply sha'));
    }

    const github = setupGithub(config.token);
    const ghDetails = ghUrlToObject(pkg.repository.url, { enterprise: true });

    const statusUpdate = {
      user: ghDetails.user,
      repo: ghDetails.repo,
      sha: config.sha,
      context: config.context || 'deployment',
      state: config.state,
      target_url: config.targetUrl,
      description: config.description
    };

    github.repos.createStatus(statusUpdate, (err, res) => {
      if (err) return reject(err);
      return resolve();
    });
  });
};
```
