### ISSUE TITLE
Current date is not selectable with custom disabled date 

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#162]
Please walk through the following steps for reporting an issue about Orion:

## Short description of your issue:

The current date cannot be selected when their is a custom disabled date. I'm not sure if any custom disabled date but it's definitely this one. See https://gomix.com/#!/project/rapid-geometry for source code.

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Visit https://rapid-geometry.gomix.me/
2. Open date picker
3. Press right arrow key to jump ahead
4. Press left arrow key to try to go back to the current date
5. Try clicking the current date

Expected: navigating "back" over disabled dates should work
Expected: clicking current date should work

## What browsers are affected?

N/A

## Which Orion version is affected?

N/A

Blocks #77

**Comment by camwest** [comment]
@aneyzberg this is still broken. See the attached animation: 
![keystroke-bug](https://cloud.githubusercontent.com/assets/22905/23963856/d701d68a-096f-11e7-9b01-d96d4464f57e.gif)


Problems:

1. I cannot select the current date
2. Two dates are disabled when isEnabled is specifying only a single date
3. I can't press the left arrow key to skip back to the current date

**Comment by aneyzberg** [comment]
@camwest hmmm strange. Taking a look now

**Comment by camwest** [comment]
I fixed the example here https://glitch.com/edit/#!/rapid-geometry and I've still got issues 1 and 3 above.

**Comment by camwest** [comment]
After discussing with @aneyzberg I still had a bug in the example. It's been fixed and there is no bug!
