### ISSUE TITLE
Placeholder does not disappear after selection in Safari

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#163]
Please walk through the following steps for reporting an issue about Orion:

## Short description of your issue:

![placeholder-persists](https://cloud.githubusercontent.com/assets/22905/23731252/5a3f2948-0421-11e7-9aa0-94fb90802290.gif)

See source code: https://gomix.com/#!/project/elegant-bait

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Visit https://elegant-bait.gomix.me/ in Safari
2. Click inside the input and select a date
3. Notice the placeholder is still visible

## What browsers are affected?

Safari

## Which Orion version is affected?

N/A

Blocks #75

**Comment by nfiniteset** [comment]
I can't reproduce this one either in Safari 10.0.3
![ezgif-1-5746c67dc5](https://cloud.githubusercontent.com/assets/178653/23816286/d8c28a32-05a0-11e7-932c-995c682d1b23.gif)
