### ISSUE TITLE
Safari placeholder disappears on searchable select

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#165]
Please walk through the following steps for reporting an issue about Orion:

## Short description of your issue:

Choosing an option from the select makes the placeholder disappear in Safari:

![safari-search-select](https://cloud.githubusercontent.com/assets/22905/23732034/a103d08c-0425-11e7-81e4-8afd404df534.gif)

See sourcecode: https://gomix.com/#!/project/pastoral-william

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Visit https://pastoral-william.gomix.me/
2. Search for something in the select in Safari
3. Notice the placeholder disappears

Expected: The selected option should be visible in the input after selecting it

## What browsers are affected?

Safari

## Which Orion version is affected?

N/A

Blocks #49

**Comment by nfiniteset** [comment]
Cam. Sorry to be the bug denier again, but we can't reproduce this one. Here I am attempting it in Safari 10.0.3.

![ezgif-1-e75e2e8a16](https://cloud.githubusercontent.com/assets/178653/23815327/90365bee-059c-11e7-8e75-86029500090c.gif)

**Comment by camwest** [comment]
BUG DENIER!!!
