### ISSUE TITLE
 Add code coverage reports to pull requests

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#24]
As CI
I want to inform the developers about code quality changes on PR
So that we can keep the codebase quality high.

The goal of this story is twofold:

1. Make a recommendation for a free service or set of tools which can examine our code quality
2. Implement the recommendation after feedback

**Comment by camwest** [comment]
For what it's worth we use Codacy internally at Autodesk.

**Comment by camwest** [comment]
@marclove I am still not seeing coverage reports:

![image](https://dl.dropboxusercontent.com/s/l618asqfxbdpiby/Screenshot%202017-01-17%2013.51.21.png?dl=0)

**Comment by camwest** [comment]
Also https://www.codacy.com/app/orion-ui/orion/dashboard should be the APP we configure.

**Comment by marclove** [comment]
@camwest I'm not clear what you mean "should be the codacy app we configure"? I am seeing coverage reporting at the given URL:
<img width="1194" alt="screen shot 2017-01-18 at 10 56 16 am" src="https://cloud.githubusercontent.com/assets/6705/22080083/103cb204-dd73-11e6-94fd-5a0c37ac94a5.png">

I am looking into getting per-file stats sent to codacy so we have more than the summary percentage.
