### ISSUE TITLE
Button: Add size attribute

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#31]
```
As a user
I want to adjust the size of a button
So that I can make a bigger or smaller button
```

The size attribute should be based on the typeScale defined here:

http://tachyons.io/docs/typography/scale/

We'll need to create a module for typeScale in packages/style following the convention.

**Comment by nfiniteset** [comment]
@camwest Ok with an API like `size="small"` and `and size="large"`, with the default being `medium`? Or would you rather it be based on numbers like `size="1"`? Thoughts here?

**Comment by camwest** [comment]
I don't have a strong opinion on that right now. As long as we're consistent across the board. I'm sure the designers will have a strong POV and will change it later.
