### ISSUE TITLE
Open & Close Select Menu

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#45]
```
As a user
I want to open the select menu
So that I can see a list of options inside
```

Context: A page with a text input and the select menu

Scenario: Focus

When I press tab while the text input is focused
Then I should see the select become focused

Scenario: Focus Out

When I tab from the select menu
Then I should see the text input become focused

Scenario: Open Menu via Keyboard

When I focus the select menu
And I press the down or up arrow keys
Then I should see the menu open

Scenario: Close Menu via ESC key

Given the menu is open
And I press the ESC key
Then I should see the menu close

Scenario: Open Menu via Mouse

When I click on a closed menu
Then I should see the menu open
And I should see the menu become focused

Scenario: Close Menu via clicking outside the menu

Given the menu is open
When I click outside the menu on any other element (including another OS window)
Then I should see the menu close

Scenario: Focus out closes menu

Given the menu is open
When I press tab from the select menu
Then I should see the menu close

## Done

* [x] Test automations exist for the above scenarios
* [x] Visual regression tests exist for all relevant view states
* [x] Scenarios above can be accomplished in Storybook
* [x] Scenarios above can be accomplished in React Playground
* [x] Scenarios above can be accomplished in Angular Playground
* [x] Scenarios above work in the latest Firefox, Safari, Chrome, and Edge

See https://github.com/orion-ui/orion/issues/42 for detailed interaction designs, wireframes, and other details.

**Comment by camwest** [comment]
Added `Scenario: Focus out closes menu`

**Comment by camwest** [comment]
@nfiniteset so this is blocked now until #34 is completed right?

**Comment by nfiniteset** [comment]
@camwest Correct.
