### ISSUE TITLE
Disabled Select Menu & Options 

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#47]
```
As a user
I want to avoid interacting with a disabled menu or options
So that I don't accidentally pick something that is not valid
```

Context:

Given I am on a page with a select menu
And the menu has the following options:

* Option 1
* Option 2
* Option 3

- [x] Scenario: Opening menu sets focus on the first option

When I open the menu
Then Option 1 should be focused

Context:

Given I am on a page with a text input, select menu, and another text input
And the menu has the following options:

* Option 1 (disabled)
* Option 2
* Option 3

- [x] Scenario: Disabled menu avoids focus

Given the menu is disabled
When I focus on the first text input
And I press TAB
Then I should see the second text input have focus

- [x] Scenario: Disabled menu avoids mouse interaction

Given the menu is disabled
When I click on the menu
Then nothing happens

- [x] Scenario: Opening menu sets focus on first non-disabled option

When I open the menu
Then Option 2 should be focused

- [x] Scenario: Avoiding disabled items during downward keyboard navigation

When I open the menu
And I press the down arrow key 
Then Option 3 should be focused
And I press the down arrow key
Then Option 2 should be focused

- [x] Scenario: Avoiding disabled items during upward keyboard navigation

When I open the menu
And I press the up arrow key
Then I should see Option 3 become focused

- [x] Scenario: Avoid navigating to disabled options with the mouse

When I open the menu
And I hover the cursor over Option 1
Then Option 2 should still be focused

## Done

* [x] Test automations exist for the above scenarios
* [x] Visual regression tests exist for all relevant view states
* [x] Scenarios above can be accomplished in Storybook
* [x] Scenarios above can be accomplished in React Playground
* [x] Scenarios above can be accomplished in Angular Playground
* [x] Scenarios above work in the latest Firefox, Safari, Chrome, and Edge

See https://github.com/orion-ui/orion/issues/42 for detailed interaction designs, wireframes, and other details.

**Comment by aneyzberg** [comment]
completed by #142

**Comment by camwest** [comment]
Did a complete review in all browsers. #148 was the only bug found.
