### ISSUE TITLE
Select Menu is Searchable

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#49]
```
As a user
I want to easily search through a list of options
So that I can type the option I want instead of having to click or navigate to it with a keyboard
```

Context:

Given I am on a page with a select menu
And the menu has the following options:

* Toronto
* Vancouver
* Seattle
* San Francisco
* San Rafael
* Montreal

And the menu is searchable
And the menu is closed

- [x] Scenario: Searchable menu focuses like a text input

Given I focus on the menu
Then I should see a blinking cursor appear to the left of the placeholder text

- [x] Scenario: No search results

Given I focus on the menu
And I enter "hello"
Then I should see the menu open
And I should see no results

- [x] Scenario: Search Results

Given I focus on the menu
And I enter "San"
Then I should see "San Francisco" and "San Rafael" as options
And I should see the menu shrink to the size of the two options

Context: Blurring a search query

Given I am on a page with a select menu
And the menu is searchable
And the current query is "s"

- [x] Scenario: ESC removes query

When I press ESC
Then I should see the menu close
And I should see the query disappear

- [x] Scenario: Clicking outside the menu removes query

When I click outside the menu on any other element (including another OS window)
Then I should see the menu close
And I should see the query disappear

## Done

* [x] Test automations exist for the above scenarios
* [x] Visual regression tests exist for all relevant view states
* [x] Scenarios above can be accomplished in Storybook
* [x] Scenarios above can be accomplished in React Playground
* [x] Scenarios above can be accomplished in Angular Playground
* [x] Scenarios above work in the latest Firefox, Safari, Chrome, and Edge

See https://github.com/orion-ui/orion/issues/42 for detailed interaction designs, wireframes, and other details.

**Comment by aneyzberg** [comment]
completed by #153
