### ISSUE TITLE
Datepicker: Custom Formatting

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#75]
```
As a user
I want to customize various formatting aspects of the datepicker
So that I can make it fit into my own application
```

Context: 

Given I am on a page
And there is a a datepicker

- [x] Scenario: Custom Placeholder Text

Given I have set the custom placeholder text to "__ / __ / ____"
When I have no date selected
Then I should see that value in the text input

- [x] Scenario: Custom Display Format

Given I have 2017-01-01 selected
When I set the displayFormat string to "dd MMM Do YYYY"
Then I should see "Su Jan 1st 2017" in the text input

- [x] Scenario: Custom Month Format

Given I have 2017-01-01 selected
And I have set the monthFormat string to "MM/YYYY"
When I focus the calendar
Then I should see 01/2017 as the calendar month date string

- [x] Scenario: Moment Locale Data

Given I have 2017-01-01 selected
And I have called moment.locale('zh-cn')
When I focus the calendar
Then I should see week day names set to "一","二","三","四","五","六","日"
And I should see 2017-01-01 start in the 日 column.

- [x] Scenario: Custom i18n strings

Given I have set previous month set to 前一个月
And I have set next month to 下个月
And I have set clear date to 清除日期
Then I should see those three text strings appear as the title tooltip of
  the previous month, next month, and clear date buttons

## Done

* [x] Test automations exist for the above scenarios
* [x] Visual regression tests exist for all relevant view states
* [x] Scenarios above can be accomplished in Storybook
* [x] Scenarios above can be accomplished in React Playground
* [x] Scenarios above can be accomplished in Angular Playground
* [x] Scenarios above work in the latest Firefox, Safari, Chrome, and Edge

See https://github.com/orion-ui/orion/issues/65 for detailed interaction designs, wireframes, and other details.

**Comment by nfiniteset** [comment]
@camwest Regarding _Scenario: Moment Locale Data_, we can't support a globally-set locale because our package's code gets a different instance of `moment` than our client's code does.

```js
// in App.js
moment.locale('zh-cn');
console.log(moment.locale());
=> 'zh-cn'

// in components/datepicker.js
console.log(moment.locale());
=> 'en'
```

Instead I propose adding a `locale` prop to datepicker.
We can set that locale on an instance of moment each time we format a value for display.

```js
// in components/datepicker.js
date.locale(this.state.locale).format();
=> '2017年2月23日'
```
