### ISSUE TITLE
Select keyboard interactions do not work on Select in Safari 10 

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#88]
Please walk through the following steps for reporting an issue about Orion:

## Short description of your issue:

Expected: Pressing up or down arrow while select is focused should open the menu in Safari

Actual: Nothing happens when you press up or down

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Launch react-playground
2. Click in text input
3. Tab to Select menu
4. Press down arrow key

## What browsers are affected?

Safari 10

## Which Orion version is affected?

Is this a new issue? Or was it always broken? Paste your Orion version. You can find it in the browser dev tools.

Blocks #45 #46

**Comment by aneyzberg** [comment]
The exception that we were seeing initially that was preventing us from implementing safari was the following  - 
```13:56:51.035 WARN - Exception: Unknown command: {"id":"lr4c84nz93gg","name":"mouseMoveTo","parameters":{"yoffset":0,"xoffset":0,"element":":wdc:1489611411016"}} (WARNING: The server did not provide any stacktrace information) ```

The Sauce labs people said this was a selenium bug - and they said the following - 
```
We've recently added support for the newly released Selenium 3.0.1, as least for part of our cloud.  For the latest version of Safari only (Safari 10 on OS X 10.12), you can use the new, built in Selenium support which _does_ allow for mouse movements.

To use Selenium 3.0.1, you'll need to add the 'seleniumVersion' desired capability to your Safari tests, setting it to '3.0.1'.
```

So I added this to our gemini.yml

```
  safari:
    desiredCapabilities:
      browserName: 'Safari'
      version: '10'
      platform: 'OS X 10.12'
      name: 'gemini visual regression tests'
      seleniumVersion: '3.0.1'
```

However this support appears to be inconsistent. And that exception is still thrown. However the main issue is it seems that the line intersections in the graph are what are failing the build as of now


![safari diff](https://cloud.githubusercontent.com/assets/5723109/24066345/f521074c-0b2e-11e7-84fc-3ed2481eef01.png)

So this issue needs to be resolved
