### ISSUE TITLE
Select menu does not open in Safari/Angular Playground

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#97]
Please walk through the following steps for reporting an issue about Orion:

## Short description of your issue:

-- Select menu does not open in Safari/Angular Playground

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. npm run compile
2. cd packages/angular-playground
3. npm start
4. Visit http://localhost:8080 in Safari 10
5. Try to click the select menu

## What browsers are affected?

All browsers? Some specific browser? What device type?

## Which Orion version is affected?

Is this a new issue? Or was it always broken? Paste your Orion version. You can find it in the browser dev tools.

Blocks #45

**Comment by aneyzberg** [comment]
We've discovered that in Safari, Angular sets props on our Select before the select constructor has run.
